const Api = [
    {
      name: "Lionel Andres Messi",
      team: "Paris Saint Germain",
      league: "League 1",
      catenaccio_name: "Lionel Messi",
      catenaccio_points: "45/15",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Paris Saint Germain",
      team_country: "Paris Saint Germain (France)",
      league_code: "FRA1",
      league_start_year: 2021,
      season: "2021-22",
      position: "RW",
      minutes: 737,
      goal: 1,
      x_gdar: 0.08,
      x_gfar: 0.09,
      x_gaar: -0.01,
      link: 90,
      forward: 51,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 61,
      def_quant: 2,
      attack_bp: 84,
      attack_sc: 94,
      carry: 38,
      shoot: 36,
      receive: 16,
      pass1: 87,
      pass2: 85,
      pass3: 46,
      aerial: 9,
      cross: 24,
      disrupt: 1,
      recover: 15,
      ball_ret: 63,
      attack: 89,
      attack_op_bp: 90,
      attack_op_sc: 93,
      attack_db_sc: 96,
      attack_db_bp: 92,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 87.61100452,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 61,
      x_g_shots_perc: 83,
      x_g_pass_bp_perc: 77,
      x_g_cross_sc_perc: 63,
      x_g_indv_takeon_bp_perc: 75,
      x_g_indv_carry_bp_perc: 79,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Paris Saint Germain",
      league: "UEFA Champions League",
      catenaccio_name: "Lionel Messi",
      catenaccio_points: "45/15",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Paris Saint Germain",
      team_country: "Paris Saint Germain (Europe)",
      league_code: "UCL",
      league_start_year: 2021,
      season: "2021-22",
      position: "RW",
      minutes: 346,
      goal: 1,
      x_gdar: -0.1,
      x_gfar: -0.06,
      x_gaar: -0.04,
      link: 89,
      forward: 38,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 6,
      def_quant: 14,
      attack_bp: 18,
      attack_sc: 21,
      carry: 55,
      shoot: 9,
      receive: 4,
      pass1: 93,
      pass2: 78,
      pass3: 27,
      aerial: 8,
      cross: 33,
      disrupt: 17,
      recover: 0,
      ball_ret: 92,
      attack: 19,
      attack_op_bp: 14,
      attack_op_sc: 25,
      attack_db_sc: 36,
      attack_db_bp: 37,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 28.94120649,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 57,
      x_g_shots_perc: 71,
      x_g_pass_bp_perc: 72,
      x_g_cross_sc_perc: 77,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 66,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2020,
      season: "2020-21",
      position: "RW",
      minutes: 397,
      goal: 1,
      x_gdar: 0.21,
      x_gfar: 0.18,
      x_gaar: 0.03,
      link: 64,
      forward: 42,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 91,
      def_quant: 19,
      attack_bp: 98,
      attack_sc: 98,
      carry: 69,
      shoot: 98,
      receive: 72,
      pass1: 70,
      pass2: 56,
      pass3: 44,
      aerial: 26,
      cross: 27,
      disrupt: 3,
      recover: 3,
      ball_ret: 86,
      attack: 98,
      attack_op_bp: 97,
      attack_op_sc: 96,
      attack_db_sc: 97,
      attack_db_bp: 94,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 97.66859931,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 85,
      x_g_shots_perc: 90,
      x_g_pass_bp_perc: 87,
      x_g_cross_sc_perc: 87,
      x_g_indv_takeon_bp_perc: 97,
      x_g_indv_carry_bp_perc: 95,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2020,
      season: "2020-21",
      position: "RW",
      minutes: 57,
      goal: 0,
      x_gdar: -0.01,
      x_gfar: 0.03,
      x_gaar: -0.04,
      link: 94,
      forward: 25,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 21,
      def_quant: 6,
      attack_bp: 92,
      attack_sc: 33,
      carry: 34,
      shoot: 57,
      receive: 63,
      pass1: 99,
      pass2: 29,
      pass3: 34,
      aerial: 7,
      cross: 24,
      disrupt: 4,
      recover: 9,
      ball_ret: 98,
      attack: 62,
      attack_op_bp: 85,
      attack_op_sc: 27,
      attack_db_sc: 32,
      attack_db_bp: 84,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 65.14274631,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 80,
      x_g_shots_perc: 63,
      x_g_pass_bp_perc: 89,
      x_g_cross_sc_perc: 79,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 77,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2019,
      season: "2019-20",
      position: "RW",
      minutes: 1825,
      goal: 17,
      x_gdar: 0.14,
      x_gfar: 0.12,
      x_gaar: 0.02,
      link: 43,
      forward: 78,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 84,
      def_quant: 31,
      attack_bp: 95,
      attack_sc: 95,
      carry: 63,
      shoot: 81,
      receive: 36,
      pass1: 40,
      pass2: 62,
      pass3: 72,
      aerial: 16,
      cross: 46,
      disrupt: 5,
      recover: 5,
      ball_ret: 57,
      attack: 95,
      attack_op_bp: 94,
      attack_op_sc: 95,
      attack_db_sc: 97,
      attack_db_bp: 97,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 93.50730594,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 77,
      x_g_shots_perc: 90,
      x_g_pass_bp_perc: 85,
      x_g_cross_sc_perc: 78,
      x_g_indv_takeon_bp_perc: 91,
      x_g_indv_carry_bp_perc: 88,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2019,
      season: "2019-20",
      position: "RW",
      minutes: 393,
      goal: 3,
      x_gdar: 0.11,
      x_gfar: 0.08,
      x_gaar: 0.03,
      link: 60,
      forward: 57,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 78,
      def_quant: 69,
      attack_bp: 90,
      attack_sc: 86,
      carry: 88,
      shoot: 69,
      receive: 40,
      pass1: 38,
      pass2: 69,
      pass3: 69,
      aerial: 18,
      cross: 24,
      disrupt: 3,
      recover: 1,
      ball_ret: 71,
      attack: 88,
      attack_op_bp: 92,
      attack_op_sc: 85,
      attack_db_sc: 89,
      attack_db_bp: 93,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 91.02056008,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 80,
      x_g_shots_perc: 81,
      x_g_pass_bp_perc: 79,
      x_g_cross_sc_perc: 74,
      x_g_indv_takeon_bp_perc: 94,
      x_g_indv_carry_bp_perc: 88,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2018,
      season: "2018-19",
      position: "RW",
      minutes: 1939,
      goal: 21,
      x_gdar: 0.2,
      x_gfar: 0.18,
      x_gaar: 0.02,
      link: 58,
      forward: 66,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 71,
      def_quant: 63,
      attack_bp: 98,
      attack_sc: 98,
      carry: 59,
      shoot: 90,
      receive: 32,
      pass1: 51,
      pass2: 47,
      pass3: 78,
      aerial: 13,
      cross: 28,
      disrupt: 8,
      recover: 6,
      ball_ret: 64,
      attack: 98,
      attack_op_bp: 98,
      attack_op_sc: 98,
      attack_db_sc: 97,
      attack_db_bp: 94,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 97.12864817,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 76,
      x_g_shots_perc: 89,
      x_g_pass_bp_perc: 84,
      x_g_cross_sc_perc: 81,
      x_g_indv_takeon_bp_perc: 93,
      x_g_indv_carry_bp_perc: 93,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2018,
      season: "2018-19",
      position: "RW",
      minutes: 572,
      goal: 7,
      x_gdar: 0.14,
      x_gfar: 0.11,
      x_gaar: 0.03,
      link: 56,
      forward: 79,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 92,
      def_quant: 15,
      attack_bp: 88,
      attack_sc: 96,
      carry: 41,
      shoot: 84,
      receive: 32,
      pass1: 45,
      pass2: 38,
      pass3: 91,
      aerial: 11,
      cross: 20,
      disrupt: 61,
      recover: 20,
      ball_ret: 83,
      attack: 92,
      attack_op_bp: 93,
      attack_op_sc: 97,
      attack_db_sc: 93,
      attack_db_bp: 80,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 93.50730594,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 83,
      x_g_shots_perc: 92,
      x_g_pass_bp_perc: 73,
      x_g_cross_sc_perc: 78,
      x_g_indv_takeon_bp_perc: 92,
      x_g_indv_carry_bp_perc: 86,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2017,
      season: "2017-18",
      position: "RW",
      minutes: 182,
      goal: 1,
      x_gdar: 0.26,
      x_gfar: 0.23,
      x_gaar: 0.03,
      link: 45,
      forward: 26,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 70,
      def_quant: 90,
      attack_bp: 99,
      attack_sc: 99,
      carry: 98,
      shoot: 99,
      receive: 96,
      pass1: 71,
      pass2: 71,
      pass3: 5,
      aerial: 22,
      cross: 11,
      disrupt: 3,
      recover: 0,
      ball_ret: 57,
      attack: 99,
      attack_op_bp: 99,
      attack_op_sc: 99,
      attack_db_sc: 99,
      attack_db_bp: 99,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 99.14796059,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 90,
      x_g_shots_perc: 96,
      x_g_pass_bp_perc: 71,
      x_g_cross_sc_perc: 1,
      x_g_indv_takeon_bp_perc: 98,
      x_g_indv_carry_bp_perc: 90,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2017,
      season: "2017-18",
      position: "RW",
      minutes: 5,
      goal: 0,
      x_gdar: 0.11,
      x_gfar: 0.1,
      x_gaar: 0.01,
      link: 10,
      forward: 99,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 92,
      def_quant: 2,
      attack_bp: 99,
      attack_sc: 57,
      carry: 21,
      shoot: 99,
      receive: 1,
      pass1: 78,
      pass2: 99,
      pass3: 7,
      aerial: 7,
      cross: 6,
      disrupt: 99,
      recover: 0,
      ball_ret: 1,
      attack: 78,
      attack_op_bp: 99,
      attack_op_sc: 53,
      attack_db_sc: 0,
      attack_db_bp: 0,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 91.02056008,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 93,
      x_g_shots_perc: 88,
      x_g_pass_bp_perc: 98,
      x_g_cross_sc_perc: 2,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 99,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2016,
      season: "2016-17",
      position: "RW",
      minutes: 1757,
      goal: 16,
      x_gdar: 0.22,
      x_gfar: 0.2,
      x_gaar: 0.02,
      link: 41,
      forward: 67,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 78,
      def_quant: 37,
      attack_bp: 97,
      attack_sc: 99,
      carry: 74,
      shoot: 94,
      receive: 65,
      pass1: 29,
      pass2: 52,
      pass3: 78,
      aerial: 15,
      cross: 23,
      disrupt: 9,
      recover: 2,
      ball_ret: 71,
      attack: 98,
      attack_op_bp: 98,
      attack_op_sc: 99,
      attack_db_sc: 99,
      attack_db_bp: 92,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 97.95028256,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 87,
      x_g_shots_perc: 96,
      x_g_pass_bp_perc: 80,
      x_g_cross_sc_perc: 66,
      x_g_indv_takeon_bp_perc: 94,
      x_g_indv_carry_bp_perc: 91,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2016,
      season: "2016-17",
      position: "RW",
      minutes: 475,
      goal: 9,
      x_gdar: 0.22,
      x_gfar: 0.19,
      x_gaar: 0.03,
      link: 67,
      forward: 51,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 85,
      def_quant: 55,
      attack_bp: 94,
      attack_sc: 99,
      carry: 53,
      shoot: 86,
      receive: 98,
      pass1: 48,
      pass2: 64,
      pass3: 86,
      aerial: 29,
      cross: 27,
      disrupt: 36,
      recover: 16,
      ball_ret: 83,
      attack: 96,
      attack_op_bp: 92,
      attack_op_sc: 99,
      attack_db_sc: 99,
      attack_db_bp: 93,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 97.95028256,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 88,
      x_g_shots_perc: 96,
      x_g_pass_bp_perc: 85,
      x_g_cross_sc_perc: 82,
      x_g_indv_takeon_bp_perc: 85,
      x_g_indv_carry_bp_perc: 92,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Paris Saint Germain",
      league: "League 1",
      catenaccio_name: "Lionel Messi",
      catenaccio_points: "45/15",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Paris Saint Germain",
      team_country: "Paris Saint Germain (France)",
      league_code: "FRA1",
      league_start_year: 2021,
      season: "2021-22",
      position: "CF/ST",
      minutes: 683,
      goal: 4,
      x_gdar: 0.05,
      x_gfar: 0.04,
      x_gaar: 0.01,
      link: 83,
      forward: 88,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 79,
      def_quant: 35,
      attack_bp: 52,
      attack_sc: 84,
      carry: 61,
      shoot: 19,
      receive: 2,
      pass1: 63,
      pass2: 81,
      pass3: 93,
      aerial: 5,
      cross: 34,
      disrupt: 7,
      recover: 88,
      ball_ret: 90,
      attack: 68,
      attack_op_bp: 53,
      attack_op_sc: 72,
      attack_db_sc: 95,
      attack_db_bp: 84,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 82.95659072,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 35,
      x_g_shots_perc: 77,
      x_g_pass_bp_perc: 88,
      x_g_cross_sc_perc: 88,
      x_g_indv_takeon_bp_perc: 90,
      x_g_indv_carry_bp_perc: 72,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Paris Saint Germain",
      league: "UEFA Champions League",
      catenaccio_name: "Lionel Messi",
      catenaccio_points: "45/15",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Paris Saint Germain",
      team_country: "Paris Saint Germain (Europe)",
      league_code: "UCL",
      league_start_year: 2021,
      season: "2021-22",
      position: "CF/ST",
      minutes: 261,
      goal: 2,
      x_gdar: 0.11,
      x_gfar: 0.1,
      x_gaar: 0.01,
      link: 68,
      forward: 79,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 76,
      def_quant: 17,
      attack_bp: 98,
      attack_sc: 82,
      carry: 70,
      shoot: 19,
      receive: 4,
      pass1: 77,
      pass2: 84,
      pass3: 72,
      aerial: 12,
      cross: 69,
      disrupt: 75,
      recover: 88,
      ball_ret: 96,
      attack: 90,
      attack_op_bp: 97,
      attack_op_sc: 87,
      attack_db_sc: 86,
      attack_db_bp: 98,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 91.02056008,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 36,
      x_g_shots_perc: 81,
      x_g_pass_bp_perc: 92,
      x_g_cross_sc_perc: 1,
      x_g_indv_takeon_bp_perc: 87,
      x_g_indv_carry_bp_perc: 89,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2020,
      season: "2020-21",
      position: "CF/ST",
      minutes: 2174,
      goal: 19,
      x_gdar: 0.13,
      x_gfar: 0.12,
      x_gaar: 0.01,
      link: 59,
      forward: 88,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 52,
      def_quant: 72,
      attack_bp: 98,
      attack_sc: 89,
      carry: 85,
      shoot: 46,
      receive: 6,
      pass1: 45,
      pass2: 84,
      pass3: 90,
      aerial: 6,
      cross: 96,
      disrupt: 19,
      recover: 27,
      ball_ret: 94,
      attack: 93,
      attack_op_bp: 98,
      attack_op_sc: 88,
      attack_db_sc: 82,
      attack_db_bp: 96,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 92.80886429,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 53,
      x_g_shots_perc: 84,
      x_g_pass_bp_perc: 96,
      x_g_cross_sc_perc: 95,
      x_g_indv_takeon_bp_perc: 95,
      x_g_indv_carry_bp_perc: 96,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2020,
      season: "2020-21",
      position: "CF/ST",
      minutes: 301,
      goal: 1,
      x_gdar: 0.09,
      x_gfar: 0.08,
      x_gaar: 0.01,
      link: 53,
      forward: 70,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 88,
      def_quant: 8,
      attack_bp: 98,
      attack_sc: 70,
      carry: 83,
      shoot: 27,
      receive: 6,
      pass1: 56,
      pass2: 65,
      pass3: 74,
      aerial: 9,
      cross: 97,
      disrupt: 17,
      recover: 58,
      ball_ret: 98,
      attack: 84,
      attack_op_bp: 96,
      attack_op_sc: 78,
      attack_db_sc: 45,
      attack_db_bp: 82,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 88.92488563,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 62,
      x_g_shots_perc: 66,
      x_g_pass_bp_perc: 93,
      x_g_cross_sc_perc: 90,
      x_g_indv_takeon_bp_perc: 96,
      x_g_indv_carry_bp_perc: 77,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2019,
      season: "2019-20",
      position: "CF/ST",
      minutes: 918,
      goal: 3,
      x_gdar: 0.11,
      x_gfar: 0.09,
      x_gaar: 0.02,
      link: 57,
      forward: 94,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 87,
      def_quant: 42,
      attack_bp: 96,
      attack_sc: 84,
      carry: 82,
      shoot: 52,
      receive: 6,
      pass1: 75,
      pass2: 75,
      pass3: 88,
      aerial: 4,
      cross: 88,
      disrupt: 44,
      recover: 59,
      ball_ret: 95,
      attack: 90,
      attack_op_bp: 97,
      attack_op_sc: 77,
      attack_db_sc: 83,
      attack_db_bp: 96,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 91.02056008,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 49,
      x_g_shots_perc: 88,
      x_g_pass_bp_perc: 92,
      x_g_cross_sc_perc: 92,
      x_g_indv_takeon_bp_perc: 92,
      x_g_indv_carry_bp_perc: 86,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2019,
      season: "2019-20",
      position: "CF/ST",
      minutes: 294,
      goal: 0,
      x_gdar: 0.06,
      x_gfar: 0.03,
      x_gaar: 0.03,
      link: 13,
      forward: 93,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 83,
      def_quant: 79,
      attack_bp: 81,
      attack_sc: 58,
      carry: 93,
      shoot: 31,
      receive: 6,
      pass1: 2,
      pass2: 77,
      pass3: 92,
      aerial: 12,
      cross: 97,
      disrupt: 47,
      recover: 75,
      ball_ret: 86,
      attack: 69,
      attack_op_bp: 66,
      attack_op_sc: 66,
      attack_db_sc: 58,
      attack_db_bp: 79,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 84.76184485,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 46,
      x_g_shots_perc: 81,
      x_g_pass_bp_perc: 91,
      x_g_cross_sc_perc: 91,
      x_g_indv_takeon_bp_perc: 94,
      x_g_indv_carry_bp_perc: 73,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2018,
      season: "2018-19",
      position: "CF/ST",
      minutes: 630,
      goal: 8,
      x_gdar: 0.06,
      x_gfar: 0.07,
      x_gaar: -0.01,
      link: 49,
      forward: 97,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 49,
      def_quant: 16,
      attack_bp: 87,
      attack_sc: 86,
      carry: 78,
      shoot: 47,
      receive: 3,
      pass1: 23,
      pass2: 81,
      pass3: 98,
      aerial: 4,
      cross: 92,
      disrupt: 0,
      recover: 49,
      ball_ret: 92,
      attack: 86,
      attack_op_bp: 77,
      attack_op_sc: 72,
      attack_db_sc: 69,
      attack_db_bp: 66,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 84.76184485,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 45,
      x_g_shots_perc: 82,
      x_g_pass_bp_perc: 91,
      x_g_cross_sc_perc: 85,
      x_g_indv_takeon_bp_perc: 91,
      x_g_indv_carry_bp_perc: 82,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2018,
      season: "2018-19",
      position: "CF/ST",
      minutes: 276,
      goal: 4,
      x_gdar: 0.05,
      x_gfar: 0.09,
      x_gaar: -0.04,
      link: 43,
      forward: 99,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 0,
      def_quant: 0,
      attack_bp: 94,
      attack_sc: 89,
      carry: 49,
      shoot: 42,
      receive: 7,
      pass1: 32,
      pass2: 69,
      pass3: 99,
      aerial: 11,
      cross: 54,
      disrupt: 11,
      recover: 67,
      ball_ret: 94,
      attack: 91,
      attack_op_bp: 93,
      attack_op_sc: 90,
      attack_db_sc: 69,
      attack_db_bp: 70,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 82.95659072,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 35,
      x_g_shots_perc: 84,
      x_g_pass_bp_perc: 96,
      x_g_cross_sc_perc: 92,
      x_g_indv_takeon_bp_perc: 86,
      x_g_indv_carry_bp_perc: 81,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2017,
      season: "2017-18",
      position: "CF/ST",
      minutes: 2814,
      goal: 30,
      x_gdar: 0.18,
      x_gfar: 0.17,
      x_gaar: 0.01,
      link: 42,
      forward: 93,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 65,
      def_quant: 43,
      attack_bp: 99,
      attack_sc: 97,
      carry: 92,
      shoot: 56,
      receive: 7,
      pass1: 48,
      pass2: 64,
      pass3: 89,
      aerial: 4,
      cross: 74,
      disrupt: 12,
      recover: 91,
      ball_ret: 92,
      attack: 98,
      attack_op_bp: 98,
      attack_op_sc: 97,
      attack_db_sc: 97,
      attack_db_bp: 98,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 96.04455209,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 58,
      x_g_shots_perc: 93,
      x_g_pass_bp_perc: 89,
      x_g_cross_sc_perc: 84,
      x_g_indv_takeon_bp_perc: 99,
      x_g_indv_carry_bp_perc: 92,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2017,
      season: "2017-18",
      position: "CF/ST",
      minutes: 765,
      goal: 6,
      x_gdar: 0.07,
      x_gfar: 0.05,
      x_gaar: 0.02,
      link: 49,
      forward: 97,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 81,
      def_quant: 51,
      attack_bp: 93,
      attack_sc: 58,
      carry: 89,
      shoot: 26,
      receive: 12,
      pass1: 67,
      pass2: 41,
      pass3: 95,
      aerial: 8,
      cross: 88,
      disrupt: 11,
      recover: 89,
      ball_ret: 90,
      attack: 75,
      attack_op_bp: 93,
      attack_op_sc: 50,
      attack_db_sc: 43,
      attack_db_bp: 75,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 86.26986374,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 42,
      x_g_shots_perc: 64,
      x_g_pass_bp_perc: 87,
      x_g_cross_sc_perc: 90,
      x_g_indv_takeon_bp_perc: 93,
      x_g_indv_carry_bp_perc: 93,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2016,
      season: "2016-17",
      position: "CF/ST",
      minutes: 985,
      goal: 13,
      x_gdar: 0.17,
      x_gfar: 0.18,
      x_gaar: -0.01,
      link: 28,
      forward: 99,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 34,
      def_quant: 32,
      attack_bp: 99,
      attack_sc: 99,
      carry: 94,
      shoot: 67,
      receive: 14,
      pass1: 10,
      pass2: 88,
      pass3: 98,
      aerial: 4,
      cross: 74,
      disrupt: 16,
      recover: 68,
      ball_ret: 92,
      attack: 99,
      attack_op_bp: 99,
      attack_op_sc: 99,
      attack_db_sc: 98,
      attack_db_bp: 99,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 95.37371958,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 63,
      x_g_shots_perc: 86,
      x_g_pass_bp_perc: 91,
      x_g_cross_sc_perc: 90,
      x_g_indv_takeon_bp_perc: 97,
      x_g_indv_carry_bp_perc: 90,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2016,
      season: "2016-17",
      position: "CF/ST",
      minutes: 349,
      goal: 0,
      x_gdar: 0,
      x_gfar: 0,
      x_gaar: 0,
      link: 14,
      forward: 99,
      dribble: 96,
      open: 30,
      set: 42,
      tackle: 62,
      def_qual: 76,
      def_quant: 8,
      attack_bp: 73,
      attack_sc: 34,
      carry: 85,
      shoot: 16,
      receive: 5,
      pass1: 16,
      pass2: 43,
      pass3: 99,
      aerial: 13,
      cross: 99,
      disrupt: 95,
      recover: 36,
      ball_ret: 97,
      attack: 53,
      attack_op_bp: 78,
      attack_op_sc: 30,
      attack_db_sc: 19,
      attack_db_bp: 26,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 68.25891094,
      open_foot: 52,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 33,
      x_g_shots_perc: 56,
      x_g_pass_bp_perc: 92,
      x_g_cross_sc_perc: 0,
      x_g_indv_takeon_bp_perc: 88,
      x_g_indv_carry_bp_perc: 84,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Paris Saint Germain",
      league: "League 1",
      catenaccio_name: "Lionel Messi",
      catenaccio_points: "45/15",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Paris Saint Germain",
      team_country: "Paris Saint Germain (France)",
      league_code: "FRA1",
      league_start_year: 2021,
      season: "2021-22",
      position: "CAM/SS",
      minutes: 775,
      goal: 1,
      x_gdar: 0.09,
      x_gfar: 0.07,
      x_gaar: 0.02,
      link: 95,
      forward: 29,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 82,
      def_quant: 31,
      attack_bp: 63,
      attack_sc: 94,
      carry: 24,
      shoot: 55,
      receive: 36,
      pass1: 84,
      pass2: 83,
      pass3: 52,
      aerial: 8,
      cross: 13,
      disrupt: 12,
      recover: 34,
      ball_ret: 96,
      attack: 78,
      attack_op_bp: 80,
      attack_op_sc: 92,
      attack_db_sc: 91,
      attack_db_bp: 55,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 88.92488563,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 59,
      x_g_shots_perc: 86,
      x_g_pass_bp_perc: 83,
      x_g_cross_sc_perc: 72,
      x_g_indv_takeon_bp_perc: 89,
      x_g_indv_carry_bp_perc: 68,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Paris Saint Germain",
      league: "UEFA Champions League",
      catenaccio_name: "Lionel Messi",
      catenaccio_points: "45/15",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Paris Saint Germain",
      team_country: "Paris Saint Germain (Europe)",
      league_code: "UCL",
      league_start_year: 2021,
      season: "2021-22",
      position: "CAM/SS",
      minutes: 21,
      goal: 0,
      x_gdar: -0.11,
      x_gfar: -0.11,
      x_gaar: 0,
      link: 99,
      forward: 31,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 92,
      def_quant: 0,
      attack_bp: 4,
      attack_sc: 8,
      carry: 1,
      shoot: 0,
      receive: 1,
      pass1: 99,
      pass2: 99,
      pass3: 2,
      aerial: 4,
      cross: 8,
      disrupt: 1,
      recover: 0,
      ball_ret: 97,
      attack: 6,
      attack_op_bp: 5,
      attack_op_sc: 9,
      attack_db_sc: 0,
      attack_db_bp: 0,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 24.68031048,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 71,
      x_g_shots_perc: 0,
      x_g_pass_bp_perc: 45,
      x_g_cross_sc_perc: 0,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 0,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2020,
      season: "2020-21",
      position: "CAM/SS",
      minutes: 572,
      goal: 7,
      x_gdar: 0.26,
      x_gfar: 0.23,
      x_gaar: 0.03,
      link: 81,
      forward: 20,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 90,
      def_quant: 30,
      attack_bp: 99,
      attack_sc: 99,
      carry: 74,
      shoot: 94,
      receive: 37,
      pass1: 92,
      pass2: 66,
      pass3: 18,
      aerial: 18,
      cross: 28,
      disrupt: 9,
      recover: 1,
      ball_ret: 82,
      attack: 99,
      attack_op_bp: 98,
      attack_op_sc: 99,
      attack_db_sc: 99,
      attack_db_bp: 98,
      hot: 1,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 99.14796059,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 83,
      x_g_shots_perc: 95,
      x_g_pass_bp_perc: 94,
      x_g_cross_sc_perc: 80,
      x_g_indv_takeon_bp_perc: 97,
      x_g_indv_carry_bp_perc: 97,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2020,
      season: "2020-21",
      position: "CAM/SS",
      minutes: 202,
      goal: 0,
      x_gdar: 0.19,
      x_gfar: 0.13,
      x_gaar: 0.06,
      link: 93,
      forward: 19,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 90,
      def_quant: 97,
      attack_bp: 93,
      attack_sc: 97,
      carry: 67,
      shoot: 87,
      receive: 11,
      pass1: 72,
      pass2: 78,
      pass3: 55,
      aerial: 7,
      cross: 35,
      disrupt: 25,
      recover: 8,
      ball_ret: 97,
      attack: 95,
      attack_op_bp: 95,
      attack_op_sc: 98,
      attack_db_sc: 93,
      attack_db_bp: 86,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 96.70088105,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 83,
      x_g_shots_perc: 88,
      x_g_pass_bp_perc: 81,
      x_g_cross_sc_perc: 88,
      x_g_indv_takeon_bp_perc: 85,
      x_g_indv_carry_bp_perc: 91,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2019,
      season: "2019-20",
      position: "CAM/SS",
      minutes: 225,
      goal: 0,
      x_gdar: 0.07,
      x_gfar: 0.07,
      x_gaar: 0,
      link: 90,
      forward: 25,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 72,
      def_quant: 5,
      attack_bp: 89,
      attack_sc: 82,
      carry: 68,
      shoot: 14,
      receive: 16,
      pass1: 60,
      pass2: 97,
      pass3: 43,
      aerial: 16,
      cross: 65,
      disrupt: 1,
      recover: 1,
      ball_ret: 89,
      attack: 85,
      attack_op_bp: 65,
      attack_op_sc: 73,
      attack_db_sc: 80,
      attack_db_bp: 86,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 86.26986374,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 60,
      x_g_shots_perc: 77,
      x_g_pass_bp_perc: 90,
      x_g_cross_sc_perc: 96,
      x_g_indv_takeon_bp_perc: 94,
      x_g_indv_carry_bp_perc: 83,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2018,
      season: "2018-19",
      position: "CAM/SS",
      minutes: 207,
      goal: 2,
      x_gdar: 0.24,
      x_gfar: 0.23,
      x_gaar: 0.01,
      link: 64,
      forward: 48,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 98,
      def_quant: 0,
      attack_bp: 99,
      attack_sc: 99,
      carry: 58,
      shoot: 99,
      receive: 45,
      pass1: 83,
      pass2: 56,
      pass3: 42,
      aerial: 21,
      cross: 19,
      disrupt: 8,
      recover: 7,
      ball_ret: 26,
      attack: 99,
      attack_op_bp: 99,
      attack_op_sc: 98,
      attack_db_sc: 99,
      attack_db_bp: 98,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 98.70149614,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 64,
      x_g_shots_perc: 86,
      x_g_pass_bp_perc: 93,
      x_g_cross_sc_perc: 1,
      x_g_indv_takeon_bp_perc: 78,
      x_g_indv_carry_bp_perc: 97,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2018,
      season: "2018-19",
      position: "CAM/SS",
      minutes: 25,
      goal: 0,
      x_gdar: 0.24,
      x_gfar: 0.23,
      x_gaar: 0.01,
      link: 40,
      forward: 9,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 96,
      def_quant: 0,
      attack_bp: 99,
      attack_sc: 99,
      carry: 48,
      shoot: 99,
      receive: 99,
      pass1: 0,
      pass2: 99,
      pass3: 9,
      aerial: 6,
      cross: 6,
      disrupt: 99,
      recover: 88,
      ball_ret: 99,
      attack: 99,
      attack_op_bp: 99,
      attack_op_sc: 63,
      attack_db_sc: 96,
      attack_db_bp: 98,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 98.70149614,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 61,
      x_g_shots_perc: 92,
      x_g_pass_bp_perc: 98,
      x_g_cross_sc_perc: 0,
      x_g_indv_takeon_bp_perc: 99,
      x_g_indv_carry_bp_perc: 92,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2017,
      season: "2017-18",
      position: "CAM/SS",
      minutes: 37,
      goal: 0,
      x_gdar: -0.07,
      x_gfar: -0.09,
      x_gaar: 0.02,
      link: 88,
      forward: 97,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 54,
      def_quant: 59,
      attack_bp: 6,
      attack_sc: 12,
      carry: 34,
      shoot: 50,
      receive: 78,
      pass1: 93,
      pass2: 82,
      pass3: 97,
      aerial: 46,
      cross: 41,
      disrupt: 73,
      recover: 15,
      ball_ret: 93,
      attack: 9,
      attack_op_bp: 7,
      attack_op_sc: 5,
      attack_db_sc: 18,
      attack_db_bp: 11,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 41.95699962,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 51,
      x_g_shots_perc: 67,
      x_g_pass_bp_perc: 49,
      x_g_cross_sc_perc: 1,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 63,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2016,
      season: "2016-17",
      position: "CAM/SS",
      minutes: 122,
      goal: 2,
      x_gdar: 0.19,
      x_gfar: 0.23,
      x_gaar: -0.04,
      link: 36,
      forward: 67,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 34,
      def_quant: 55,
      attack_bp: 99,
      attack_sc: 99,
      carry: 45,
      shoot: 91,
      receive: 72,
      pass1: 34,
      pass2: 8,
      pass3: 93,
      aerial: 13,
      cross: 49,
      disrupt: 2,
      recover: 7,
      ball_ret: 95,
      attack: 99,
      attack_op_bp: 99,
      attack_op_sc: 99,
      attack_db_sc: 99,
      attack_db_bp: 99,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 96.70088105,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 89,
      x_g_shots_perc: 95,
      x_g_pass_bp_perc: 96,
      x_g_cross_sc_perc: 82,
      x_g_indv_takeon_bp_perc: 90,
      x_g_indv_carry_bp_perc: 93,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Paris Saint Germain",
      league: "League 1",
      catenaccio_name: "Lionel Messi",
      catenaccio_points: "45/15",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Paris Saint Germain",
      team_country: "Paris Saint Germain (France)",
      league_code: "FRA1",
      league_start_year: 2021,
      season: "2021-22",
      position: "RM/RWB",
      minutes: 39,
      goal: 0,
      x_gdar: -0.06,
      x_gfar: 0.06,
      x_gaar: -0.12,
      link: 93,
      forward: 54,
      dribble: 89,
      open: 42,
      set: 60,
      tackle: 34,
      def_qual: 0,
      def_quant: 3,
      attack_bp: 91,
      attack_sc: 82,
      carry: 98,
      shoot: 99,
      receive: 6,
      pass1: 92,
      pass2: 60,
      pass3: 73,
      aerial: 57,
      cross: 21,
      disrupt: 1,
      recover: 0,
      ball_ret: 7,
      attack: 86,
      attack_op_bp: 31,
      attack_op_sc: 6,
      attack_db_sc: 97,
      attack_db_bp: 99,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 46.1149729,
      open_foot: 51,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 94,
      x_g_shots_perc: 94,
      x_g_pass_bp_perc: 36,
      x_g_cross_sc_perc: 3,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 93,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2019,
      season: "2019-20",
      position: "RM/RWB",
      minutes: 25,
      goal: 0,
      x_gdar: -0.06,
      x_gfar: -0.05,
      x_gaar: -0.01,
      link: 99,
      forward: 0,
      dribble: 89,
      open: 42,
      set: 60,
      tackle: 34,
      def_qual: 90,
      def_quant: 0,
      attack_bp: 26,
      attack_sc: 12,
      carry: 74,
      shoot: 65,
      receive: 6,
      pass1: 95,
      pass2: 99,
      pass3: 2,
      aerial: 1,
      cross: 4,
      disrupt: 0,
      recover: 0,
      ball_ret: 97,
      attack: 19,
      attack_op_bp: 31,
      attack_op_sc: 9,
      attack_db_sc: 61,
      attack_db_bp: 98,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 46.1149729,
      open_foot: 51,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 63,
      x_g_shots_perc: 53,
      x_g_pass_bp_perc: 61,
      x_g_cross_sc_perc: 3,
      x_g_indv_takeon_bp_perc: 99,
      x_g_indv_carry_bp_perc: 0,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2018,
      season: "2018-19",
      position: "RM/RWB",
      minutes: 9,
      goal: 0,
      x_gdar: -0.06,
      x_gfar: -0.04,
      x_gaar: -0.02,
      link: 88,
      forward: 32,
      dribble: 89,
      open: 42,
      set: 60,
      tackle: 34,
      def_qual: 47,
      def_quant: 50,
      attack_bp: 3,
      attack_sc: 68,
      carry: 91,
      shoot: 99,
      receive: 2,
      pass1: 99,
      pass2: 0,
      pass3: 45,
      aerial: 99,
      cross: 2,
      disrupt: 0,
      recover: 0,
      ball_ret: 5,
      attack: 35,
      attack_op_bp: 4,
      attack_op_sc: 4,
      attack_db_sc: 26,
      attack_db_bp: 2,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 46.1149729,
      open_foot: 51,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 60,
      x_g_shots_perc: 86,
      x_g_pass_bp_perc: 0,
      x_g_cross_sc_perc: 1,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 0,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2017,
      season: "2017-18",
      position: "RM/RWB",
      minutes: 27,
      goal: 1,
      x_gdar: 0.17,
      x_gfar: 0.18,
      x_gaar: -0.01,
      link: 0,
      forward: 99,
      dribble: 89,
      open: 42,
      set: 60,
      tackle: 34,
      def_qual: 92,
      def_quant: 0,
      attack_bp: 99,
      attack_sc: 99,
      carry: 99,
      shoot: 99,
      receive: 3,
      pass1: 0,
      pass2: 33,
      pass3: 98,
      aerial: 62,
      cross: 80,
      disrupt: 0,
      recover: 0,
      ball_ret: 0,
      attack: 99,
      attack_op_bp: 99,
      attack_op_sc: 99,
      attack_db_sc: 99,
      attack_db_bp: 99,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 95.37371958,
      open_foot: 51,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 39,
      x_g_shots_perc: 98,
      x_g_pass_bp_perc: 98,
      x_g_cross_sc_perc: 2,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 99,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "UEFA Champions League",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Europe)",
      league_code: "UCL",
      league_start_year: 2016,
      season: "2016-17",
      position: "RM/RWB",
      minutes: 16,
      goal: 0,
      x_gdar: 0.18,
      x_gfar: 0.09,
      x_gaar: 0.09,
      link: 45,
      forward: 20,
      dribble: 89,
      open: 42,
      set: 60,
      tackle: 34,
      def_qual: 96,
      def_quant: 70,
      attack_bp: 99,
      attack_sc: 80,
      carry: 99,
      shoot: 10,
      receive: 15,
      pass1: 99,
      pass2: 0,
      pass3: 95,
      aerial: 99,
      cross: 12,
      disrupt: 99,
      recover: 0,
      ball_ret: 35,
      attack: 89,
      attack_op_bp: 99,
      attack_op_sc: 79,
      attack_db_sc: 0,
      attack_db_bp: 0,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 96.04455209,
      open_foot: 51,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 0,
      x_g_shots_perc: 0,
      x_g_pass_bp_perc: 0,
      x_g_cross_sc_perc: 2,
      x_g_indv_takeon_bp_perc: 100,
      x_g_indv_carry_bp_perc: 95,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Paris Saint Germain",
      league: "UEFA Champions League",
      catenaccio_name: "Lionel Messi",
      catenaccio_points: "45/15",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Paris Saint Germain",
      team_country: "Paris Saint Germain (Europe)",
      league_code: "UCL",
      league_start_year: 2021,
      season: "2021-22",
      position: "LW",
      minutes: 7,
      goal: 0,
      x_gdar: 0.27,
      x_gfar: 0.19,
      x_gaar: 0.08,
      link: 1,
      forward: 67,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 92,
      def_quant: 99,
      attack_bp: 99,
      attack_sc: 98,
      carry: 1,
      shoot: 99,
      receive: 1,
      pass1: 8,
      pass2: 4,
      pass3: 65,
      aerial: 4,
      cross: 8,
      disrupt: 1,
      recover: 99,
      ball_ret: 96,
      attack: 98,
      attack_op_bp: 99,
      attack_op_sc: 97,
      attack_db_sc: 0,
      attack_db_bp: 0,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 99.31553766,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 0,
      x_g_shots_perc: 94,
      x_g_pass_bp_perc: 87,
      x_g_cross_sc_perc: 2,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 85,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2020,
      season: "2020-21",
      position: "LW",
      minutes: 5,
      goal: 0,
      x_gdar: 0,
      x_gfar: 0.23,
      x_gaar: 0,
      link: 99,
      forward: 1,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 0,
      def_quant: 0,
      attack_bp: 99,
      attack_sc: 99,
      carry: 0,
      shoot: 97,
      receive: 2,
      pass1: 99,
      pass2: 0,
      pass3: 77,
      aerial: 15,
      cross: 6,
      disrupt: 0,
      recover: 0,
      ball_ret: 99,
      attack: 99,
      attack_op_bp: 99,
      attack_op_sc: 98,
      attack_db_sc: 0,
      attack_db_bp: 0,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 68.25891094,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 100,
      x_g_shots_perc: 95,
      x_g_pass_bp_perc: 95,
      x_g_cross_sc_perc: 1,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 75,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2018,
      season: "2018-19",
      position: "LW",
      minutes: 10,
      goal: 1,
      x_gdar: 0.23,
      x_gfar: 0.23,
      x_gaar: 0,
      link: 1,
      forward: 62,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 91,
      def_quant: 0,
      attack_bp: 99,
      attack_sc: 99,
      carry: 85,
      shoot: 99,
      receive: 3,
      pass1: 89,
      pass2: 64,
      pass3: 0,
      aerial: 9,
      cross: 6,
      disrupt: 0,
      recover: 0,
      ball_ret: 97,
      attack: 99,
      attack_op_bp: 99,
      attack_op_sc: 99,
      attack_db_sc: 0,
      attack_db_bp: 0,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 98.27949549,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 60,
      x_g_shots_perc: 100,
      x_g_pass_bp_perc: 60,
      x_g_cross_sc_perc: 1,
      x_g_indv_takeon_bp_perc: 100,
      x_g_indv_carry_bp_perc: 100,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2017,
      season: "2017-18",
      position: "LW",
      minutes: 85,
      goal: 0,
      x_gdar: -0.02,
      x_gfar: -0.03,
      x_gaar: 0.01,
      link: 10,
      forward: 99,
      dribble: 87,
      open: 69,
      set: 77,
      tackle: 55,
      def_qual: 94,
      def_quant: 0,
      attack_bp: 49,
      attack_sc: 23,
      carry: 48,
      shoot: 63,
      receive: 2,
      pass1: 5,
      pass2: 9,
      pass3: 99,
      aerial: 10,
      cross: 46,
      disrupt: 0,
      recover: 7,
      ball_ret: 17,
      attack: 36,
      attack_op_bp: 72,
      attack_op_sc: 18,
      attack_db_sc: 19,
      attack_db_bp: 33,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 61.86389736,
      open_foot: 42,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 53,
      x_g_shots_perc: 67,
      x_g_pass_bp_perc: 47,
      x_g_cross_sc_perc: 4,
      x_g_indv_takeon_bp_perc: 100,
      x_g_indv_carry_bp_perc: 67,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2020,
      season: "2020-21",
      position: "CM",
      minutes: 7,
      goal: 0,
      x_gdar: 0.01,
      x_gfar: -0.02,
      x_gaar: 0.03,
      link: 0,
      forward: 99,
      dribble: 89,
      open: 32,
      set: 60,
      tackle: 33,
      def_qual: 95,
      def_quant: 6,
      attack_bp: 84,
      attack_sc: 2,
      carry: 99,
      shoot: 0,
      receive: 6,
      pass1: 17,
      pass2: 0,
      pass3: 99,
      aerial: 10,
      cross: 10,
      disrupt: 0,
      recover: 0,
      ball_ret: 0,
      attack: 43,
      attack_op_bp: 99,
      attack_op_sc: 3,
      attack_db_sc: 2,
      attack_db_bp: 22,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 73.65964555,
      open_foot: 54,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 80,
      x_g_shots_perc: 0,
      x_g_pass_bp_perc: 96,
      x_g_cross_sc_perc: 2,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 0,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    },
    {
      name: "Lionel Andres Messi",
      team: "Barcelona",
      league: "Laliga",
      catenaccio_name: "",
      catenaccio_points: "",
      age: 35,
      height: 170,
      weight: 72,
      birthdate: "06/24/1987",
      name_dob: "Lionel Andres Messi (24.06.1987)",
      field_name: "L.A Messi",
      team_short_name: "Barcelona",
      team_country: "Barcelona (Spain)",
      league_code: "SPA1",
      league_start_year: 2019,
      season: "2019-20",
      position: "CM",
      minutes: 3,
      goal: 0,
      x_gdar: 0,
      x_gfar: -0.06,
      x_gaar: 0,
      link: 2,
      forward: 99,
      dribble: 89,
      open: 32,
      set: 60,
      tackle: 33,
      def_qual: 0,
      def_quant: 0,
      attack_bp: 27,
      attack_sc: 2,
      carry: 92,
      shoot: 3,
      receive: 3,
      pass1: 99,
      pass2: 54,
      pass3: 0,
      aerial: 5,
      cross: 99,
      disrupt: 0,
      recover: 0,
      ball_ret: 97,
      attack: 14,
      attack_op_bp: 24,
      attack_op_sc: 3,
      attack_db_sc: 2,
      attack_db_bp: 4,
      hot: 0,
      cold: 0,
      breakout: 0,
      underused: 0,
      prospect: 0,
      x_gdar_perc: 68.25891094,
      open_foot: 54,
      open_head: 0,
      dead_foot: 0,
      dead_head: 0,
      x_g_receive_bp_perc: 0,
      x_g_shots_perc: 0,
      x_g_pass_bp_perc: 95,
      x_g_cross_sc_perc: 0,
      x_g_indv_takeon_bp_perc: 0,
      x_g_indv_carry_bp_perc: 0,
      claimpct: 0,
      claimpercross_perc: 0,
      passpct1: 0,
      passpct2: 0,
      passpct3: 0
    }
  ];

  export default Api;